stages:
  - verify
  - deploy

include:
  - project: 'acquiring/devops/pipelines'
    ref: master
    file: '.appsec.yml'

variables:
  APP_NAME: ecom-sdk-java
  APPSEC_TEAM_ID: 47

push:
  stage: deploy
  script:
    - git config --global user.email $OPEN_SOURCE_GITHUB_EMAIL
    - git config --global user.name $OPEN_SOURCE_GITHUB_LOGIN
    - git push https://$OPEN_SOURCE_GITHUB_LOGIN:$OPEN_SOURCE_GITHUB_TOKEN_NODE@github.com/Raiffeisen-DGTL/$APP_NAME.git HEAD:main
  only:
    - master
